### ISSUE TITLE
locationEnabled always return false in listener 

### ISSUE THREAD

**Issue by ohszehong** [YsnKsy/react-native-location-enabler#196]
let _gpsState = LocationEnabler.addListener(({ locationEnabled }) => {
      console.log('location is enabled: ', locationEnabled);
      setGpsState(locationEnabled);
    });

^ When I called checkSettings() function, this will be triggered, however for some of the android phone, it is working properly, but for some other android phone like realme C35, it always return false

**Comment by kulcsarrudolf** [comment]
@ohszehong Did you find a solution to the problem? Because it is not working for me either.

**Comment by kulcsarrudolf** [comment]
@ohszehong Did you find a solution to the problem? Because it is not working for me either.

**Comment by kulcsarrudolf** [comment]
@YsnKsy Could you provide an example of how to use an event listener to retrieve the location status?

**Comment by YsnKsy** [comment]
> @YsnKsy Could you provide an example of how to use an event listener to retrieve the location status?

@kulcsarrudolf Read the README.md an example is provided.

**Comment by YsnKsy** [comment]
> let _gpsState = LocationEnabler.addListener(({ locationEnabled }) => {
> 
>       console.log('location is enabled: ', locationEnabled);
> 
>       setGpsState(locationEnabled);
> 
>     });
> 
> 
> 
> ^ When I called checkSettings() function, this will be triggered, however for some of the android phone, it is working properly, but for some other android phone like realme C35, it always return false

@ohszehong Maybe you don't have a Google Play Store installed ? because this packages need Google Play services to work properly.
