### ISSUE TITLE
HI app crash due to onActivityResult receiving null intent

### ISSUE THREAD

**Issue by ANIBIT14** [YsnKsy/react-native-location-enabler#30]
Hi the app was getting following error :-
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=1024, result=0, data=null} to activity {com.creditcard.onecard/com.creditcard.onecard.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method k.b0.d.k.d, parameter intent, as intent had no null handling, 

I have added it in this fork: -https://github.com/ANIBIT14/react-native-location-enabler/tree/master/android/src/main/java/com/reactnativelocationenabler, you can check and update the code, in this package @YsnKsy

**Comment by YsnKsy** [comment]
Hi @ANIBIT14 

Please provide all the information requested : 
- Run react-native info in your terminal and copy the results here.
- Provide a detailed list of steps that reproduce the issue.

**Comment by ANIBIT14** [comment]
Hi @YsnKsy 

- System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 462.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.5.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_261 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found


- My app is using two intents, in a flow where location intent is not being consumed and an intent for screen overlay permission is accessed and user comes back from the setting to the app, location intent get's null and it causes a crash, because handling for null intent was not present.

**Comment by ANIBIT14** [comment]
@YsnKsy Hi, it would be great that if you can explain what change does this brings in scope /- val locationRequest = LocationRequest.create().setPriority(priority) from the .apply() code

**Comment by YsnKsy** [comment]
> @YsnKsy Hi, it would be great that if you can explain what change does this brings in scope /- val locationRequest = LocationRequest.create().setPriority(priority) from the .apply() code

it does not bring any change, apart a one less warning during the build.

It would be great that if you can press Start button to the repo 😉
