### ISSUE TITLE
Issue in IOS

### ISSUE THREAD

**Issue by darshanksexathought** [YsnKsy/react-native-location-enabler#88]
`Invariant Violation: Native module cannot be null.[Mon Jul 05 2021 21:07:01.759]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)[Mon Jul 05 2021 21:07:02.849]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

Getting this error while  running on IOS

**Comment by Jurpp** [comment]
@YsnKsy Would you be willing to look into this? 
@darshanksexathought the following (ugly) workaround works for me:
Instead of:
```
import { AppState, Platform } from 'react-native';
[..All other imports..]
import LocationEnabler from "react-native-location-enabler";
```
do:
```
import { AppState, Platform } from 'react-native';
[..All other imports..]
var LocationEnabler = (Platform.OS === 'android') ? require('react-native-location-enabler') : null;
```

**Comment by Jurpp** [comment]
Does not look like author is going to merge my PR. Feel free to use my fork though :)

**Comment by bmbmjmdm** [comment]
Thanks a bunch Jurpp! For anyone reading this in the future, you'll also need to add this to your project's Podfile: 
`pod 'react-native-location-enabler', :path => '../node_modules/react-native-location-enabler/ios'`

**Comment by dhairyasenjaliya** [comment]
> Thanks a bunch Jurpp! For anyone reading this in the future, you'll also need to add this to your project's Podfile: `pod 'react-native-location-enabler', :path => '../node_modules/react-native-location-enabler/ios'`

there is no iOS folder in package

**Comment by bmbmjmdm** [comment]
Hi @dhairyasenjaliya , I was referring to Jurpp's fork at the time. However it looks like the devs have patched this issue so there's no need for either!

**Comment by praveenbalajia** [comment]
@Jurpp 
I used 4.1.1 the same issue happened in iOS so I used your fork 
The issue still persists can you please identify what the code changes have to be done for iOS

```
import LocationEnabler from 'react-native-location-enabler'

const {
    useLocationSettings,
    PRIORITIES: { HIGH_ACCURACY },
  } = LocationEnabler
const [enabled, requestResolution] =  useLocationSettings({
    priority: HIGH_ACCURACY, // optional: default BALANCED_POWER_ACCURACY
    alwaysShow: true, // optional: default false
    needBle: true, // optional: default false
})
```

**Comment by faustoct1** [comment]
still happening `Invariant Violation: new NativeEventEmitter() requires a non-null argument.`

**Comment by mak12** [comment]
Any update on this?, issue is still there.

**Comment by devselleri** [comment]
figured out!
after use this `var LocationEnabler = (Platform.OS === 'android') ? require('react-native-location-enabler') : null;` I got `HIGH_ACCURACY` has undefined value, so there is `default` object to destruct the properties, see the code as follow:

`const {
    PRIORITIES: { HIGH_ACCURACY },
    useLocationSettings,
  } = LocationEnabler.default;`




> @YsnKsy Would you be willing to look into this? @darshanksexathought the following (ugly) workaround works for me: Instead of:
> 
> ```
> import { AppState, Platform } from 'react-native';
> [..All other imports..]
> import LocationEnabler from "react-native-location-enabler";
> ```
> 
> do:
> 
> ```
> import { AppState, Platform } from 'react-native';
> [..All other imports..]
> var LocationEnabler = (Platform.OS === 'android') ? require('react-native-location-enabler') : null;
> ```
> 
> Update: This workaround doesn't behave as expected either.
> 
> Update2: This seemed like a fun way to learn some more React Native so I started implementing this myself: https://github.com/Jurpp/react-native-location-enabler I will submit a PR when its finished.

**Comment by jumandika** [comment]
figured out!
after use this solution
`var LocationEnabler = (Platform.OS === 'android') ? require('react-native-location-enabler') : null;` 

I got `HIGH_ACCURACY` has undefined value on Android, so I console.log() the value of `LocationEnabler`, 
```
{
    "default": {
        "BALANCED_POWER_ACCURACY": 102,
        "HIGH_ACCURACY": 100,
        "LOW_POWER": 104,
        "NO_POWER": 105,
        "PRIORITIES": {
            "BALANCED_POWER_ACCURACY": 102,
            "HIGH_ACCURACY": 100,
            "LOW_POWER": 104,
            "NO_POWER": 105
        },
        "addListener": [Function anonymous
        ],
        "checkSettings": [Function nonPromiseMethodWrapper
        ],
        "getConstants": [Function anonymous
        ],
        "once": [Function anonymous
        ],
        "requestResolutionSettings": [Function nonPromiseMethodWrapper
        ],
        "useLocationSettings": [Function anonymous
        ]
    }
}
```

there is `default` object to destruct the properties, see the code as follow:

```
const {
    PRIORITIES: { HIGH_ACCURACY },
    useLocationSettings,
  } = LocationEnabler.default;
```




> @YsnKsy Would you be willing to look into this? @darshanksexathought the following (ugly) workaround works for me: Instead of:
> 
> ```
> import { AppState, Platform } from 'react-native';
> [..All other imports..]
> import LocationEnabler from "react-native-location-enabler";
> ```
> 
> do:
> 
> ```
> import { AppState, Platform } from 'react-native';
> [..All other imports..]
> var LocationEnabler = (Platform.OS === 'android') ? require('react-native-location-enabler') : null;
> ```
> 
> Update: This workaround doesn't behave as expected either.
> 
> Update2: This seemed like a fun way to learn some more React Native so I started implementing this myself: https://github.com/Jurpp/react-native-location-enabler I will submit a PR when its finished.
