### ISSUE TITLE
How should permission not being granted be handled? 

### ISSUE THREAD

**Issue by jordanchaitin** [YsnKsy/react-native-location-enabler#89]
So it is quite clear in the documentation how to check if location is not enabled and ask for permission to enable it. 

But suppose, after asking for permission to enable location, the user does not grant it. And I want to show a message/alert saying because location permission was not granted, we cannot proceed further. 

How can I handle this situation?

**Comment by YsnKsy** [comment]
All you have to do is ask the user for authorization again!

I close this issue, because it is not a real issue related to this package.
